- name: Updating all packages on CentOS-RedHat-OracleLinux Servers
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Update yum repo and package cache
      yum:
        update_cache: true

    - name: List updates
      yum:
        list: updates

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Reboot the servers
      reboot:
        msg: "Rebooting the servers after applying Kernel Updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime